/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cameratest3_LaneDetectionView */

#ifndef _Included_com_example_cameratest3_LaneDetectionView
#define _Included_com_example_cameratest3_LaneDetectionView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cameratest3_LaneDetectionView
 * Method:    nativeGetROI
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_cameratest3_LaneDetectionView_nativeGetROI
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_example_cameratest3_LaneDetectionView
 * Method:    birdeye
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_cameratest3_LaneDetectionView_birdeye
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_example_cameratest3_LaneDetectionView
 * Method:    nativeDetect
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_cameratest3_LaneDetectionView_nativeDetect
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
